/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:40814541-edcc-47cc-b52e-1656262d3d60",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ghb9glKuM",
    "aws_user_pools_web_client_id": "21lc4i1i1r4a1ls9p215kmbden",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "hackatownapi",
            "endpoint": "https://axgt2jqur6.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
